site_name: ODE Documentation

nav:
  - Home: index.md
  - Reference: reference.md

markdown_extensions:
  - pymdownx.superfences

plugins:
  - search
  - include-markdown:
      encoding: utf-8
      preserve_includer_indent: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js