site_name: ODE Documentation

nav:
  - Home: index.md
  - "ODE Module": ode.md

markdown_extensions:
  - pymdownx.superfences

plugins:
  - search
  - include-markdown:
      encoding: utf-8
      preserve_includer_indent: true
